# Generated by Django 2.1.1 on 2018-10-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('fa_name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('add', models.CharField(max_length=100)),
                ('u_name', models.CharField(max_length=50)),
                ('u_pass', models.IntegerField(default=10)),
            ],
        ),
    ]
